@ECHO OFF
ECHO Installing npm dependencies...
cd /D %~dp0..\food-website-testing
ECHO current path is %~dp0..\food-website-testing
start cmd.exe /c "npm install --force"
ECHO Starting frontend...
start cmd.exe /k "npm start"
cd ./food-backend
ECHO Activating virtual environment...
\Scripts\activate.bat
ECHO Installing python dependencies...
pip install -r ./requirements.txt
ECHO Running backend server...
python ./manage.py runserver
PAUSE